name: CI
 
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
          
      # Check / use dependencies cache
          
      # Install dependencies    
      - name: Install dependencies
        run: yarn
      
      # Execute build script      
      - name: Run build
        run: yarn build

      # [Digital Ocean] Replace source-code
      - name: Replace source-code on Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules"
          target: "~/app/gobarber-backend"
      
      # [Digital Ocean] Install dependencies - Run Migrations - Restart API
      - name: Run production scripts on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
           cd ~/app/gobarber-backend
           yarn
           ./node_modules/.bin/typeorm migration:run
           pm2 restart gobarber-api
